### ISSUE TITLE
[bug] The command register seems to mask the "reload" enum

### ISSUE THREAD

**Issue by MengHanLOVE1027** [EndstoneMC/endstone#29] opened 2024-07-30 15:19 UTC
**Describe the bug**
"reload" appears to be blocked in the instruction enumeration

**To Reproduce**

1. Write content in the plugin:
   (This is the code)
```python
# 注册命令
commands = {
    # 备份主命令
    "backup": {
        "description": "test is op",
        "usages": ["/backup (init|reload)[action: OtherAction]"],
        "permissions": ["easybackuper_plugin.command.only_op"]
    }
}
# 权限组
permissions = {
    # 只有 OP 玩家才可以执行命令
    "easybackuper_plugin.command.only_op": {
        "description": "Only OP Players can use this command",
        "default": "op",
    }
}

# 处理命令
    def on_command(self, sender: CommandSender, command: Command, args: list[str]) -> bool:
        if command.name == "backup":
            if len(args) == 0:
                (It works fine here)
            else:
                # 现在是有附加参数的情况
                #  backup [init|reload]
                #       此处为 args[0]
                # 开始对其附加参数进行判断
                match args[0]:
                    case "init":
                        self.logger.info("Hello EasyBackuper!")
                        self.logger.warning(sender.name)
                    case "reload":
                        self.logger.info("Hello EasyBackuper!")
                        self.logger.warning(sender.name)
        return True
```

2. Build the plugin and place it in the 'plugins' folder.
3. Start the server.
4. Open Minecraft.
5. Go to the server and join it.
6. Type `/backup(There's a space here)` to test (after obtaining OP status).
7. See the result (see screenshot below).
![image](https://github.com/user-attachments/assets/ef704b22-94f8-4117-bd09-b3492ea5c500)
8. There is no optional parameter enumerator for reload.
9. Modifying the code (see below)
```python
    # 注册命令
    commands = {
        # 备份主命令
        "backup": {
            "description": "test is op",
            "usages": ["/backup (init|reloading)[action: OtherAction]"],
            "permissions": ["easybackuper_plugin.command.only_op"]
        }
    }

...

    case "reloading":
        self.logger.info("Hello EasyBackuper!")
        self.logger.warning(sender.name)
```
10. Check it out again (see below)
![image](https://github.com/user-attachments/assets/53e9ad36-c412-40e0-916f-3f354927c07d)

**Expected behavior**
The "reload" enum displays normally. But it didn't work.

In addition, instructions can be executed directly
By the way, sorry to trouble you. :p

**Screenshots**
See above.

**Details (please complete the following information):**
 - OS: Windows 11 x64
 - Endstone Version: v0.5.0

**Additional context**
None.

**Comment by wu-vincent** [comment] 2024-07-30 15:44
Quick question, were you able to execute the command with reload enum even it’s not displayed on the client side?

**Comment by MengHanLOVE1027** [comment] 2024-07-30 15:46
> Quick question, were you able to execute the command with reload enum even it’s not displayed on the client side?快速提问，即使它没有显示在客户端，您也能够使用 reload enum 执行命令吗？

Yes, both client and console

**Comment by smartcmd** [comment] 2024-07-30 15:48
这个问题我知道怎么修，等我打完bfv

**Comment by MengHanLOVE1027** [comment] 2024-07-30 15:49
> 这个问题我知道怎么修，等我打完bfv

可以 Chinese 嘛这里，我看没人 Chinese

**Comment by wu-vincent** [comment] 2024-07-31 14:38
<img width="902" alt="Screenshot 2024-07-31 153617" src="https://github.com/user-attachments/assets/de023164-4ec9-43c9-aac4-0a953ff3e5fa">

Fixed in https://github.com/EndstoneMC/endstone/commit/46325a32420940cccb2dfe36bdde34f1929f1847. I can confirm this is due to the "reload" command being sent to the client while the client has no permission to execute it.

**Closed by wu-vincent** 2024-07-31 14:38 UTC
Labels: bug
