### ISSUE TITLE
Crash during gameplay

### ISSUE THREAD

**Issue by Nat456Gaming** [EndstoneMC/endstone#45] opened 2024-09-03 10:12 UTC
The server software works great and it just crashed once, it says "PLEASE REPORT THIS AS AN ISSUE ON GITHUB", so I am.
I don't know where it comes from, I don't have any plugin and it crashed when 3 people were playing (nothing more than survival)
It rebooted as usual after and works great now, nothing corrupted.
I am on Linux mint 21.3, Kernel: Linux 5.15.0-119-generic
Here are the log:

=== ENDSTONE CRASHED! - PLEASE REPORT THIS AS AN ISSUE ON GITHUB ===
Operation system: Linux
Endstone version: 0.5.2
Api version     : 0.5
Description     : Signal received: 11
Stack trace (most recent call first):
#0  0x7f1e801b0d7c     (0x0002d8d7c) in endstone::detail::(anonymous namespace)::signal_handler(int, siginfo_t*, void*) at /home/runner/work/endstone/endstone/src/endstone_runtime/linux/signal_handler.cpp:33:5
#1  0x7f1e7fb2351f     (0x00004251f) at /lib/x86_64-linux-gnu/libc.so.6
#2  0x5586a758218a     (0x0069b318a) at /home/nat456/bedrock_server/bedrock_server
#3  0x5586a8286832     (0x0076b7832) at /home/nat456/bedrock_server/bedrock_server
#4  0x5586a8286de5     (0x0076b7de5) at /home/nat456/bedrock_server/bedrock_server
#5  0x5586a863cd3e     (0x007a6dd3e) at /home/nat456/bedrock_server/bedrock_server
#6  0x5586a863be85     (0x007a6ce85) at /home/nat456/bedrock_server/bedrock_server
#7  0x5586a864b353     (0x007a7c353) at /home/nat456/bedrock_server/bedrock_server
#8  0x5586a8fcad1b     (0x0083fbd1b) at /home/nat456/bedrock_server/bedrock_server
#9  0x5586a8f981e0     (0x0083c91e0) at /home/nat456/bedrock_server/bedrock_server
#10 0x5586a8f97e9f     (0x0083c8e9f) at /home/nat456/bedrock_server/bedrock_server
#11 0x5586a8fbc3c7     (0x0083ed3c7) at /home/nat456/bedrock_server/bedrock_server
#12 0x7f1e7fb75ac2     (0x000094ac2) in start_thread at ./nptl/pthread_create.c:442:8
#13 0x7f1e7fc0784f     (0x00012684f) at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81:0

**Comment by wu-vincent** [comment] 2024-09-03 11:38
Thanks. I will look into it

**Comment by wu-vincent** [comment] 2024-09-03 12:23
Thanks again for reporting this. I have reviewed the stack trace provided, and it appears that the problem originated from BDS itself and has nothing to do with Endstone.

I'm currently unable to reproduce this issue, so I will be closing this issue for now. If you manage to find a way to consistently reproduce the crash, please feel free to reopen the issue, and I will be happy to investigate further. :)

**Closed by wu-vincent** 2024-09-03 12:23 UTC
Labels: bug, wontfix
